function freshState(){return{version:3,stage:0,name:'',selections:{interest:[],ability:[],value:[],core:[],environment:[],life:[],dealbreaker:[]},skillEvidence:{},questionIds:[],conflictIndex:0,conflicts:{},followups:[],depth:{},startedAt:null,completedAt:null,updatedAt:null};}
let notice='',state=loadState(),entryView=(state.stage>0&&state.stage<12)?'resume':'',dragState=null,suppressClickUntil=0,analysisTimer=null;
function loadState(){try{const raw=localStorage.getItem(V3_KEY);if(!raw)return freshState();const s=JSON.parse(raw);if(!s||s.version!==3||!s.selections)throw Error('format');const f=freshState();Object.assign(f,s);for(const k of Object.keys(f.selections)){f.selections[k]=Array.isArray(s.selections[k])?s.selections[k].filter(id=>byId[id]):[];const max=limits[k]||99;if(f.selections[k].length>max)f.selections[k]=f.selections[k].slice(0,max);}f.skillEvidence=Object.fromEntries(Object.entries(s.skillEvidence||{}).filter(([id,v])=>f.selections.ability.includes(id)&&[1,2,3].includes(v)));if(!Array.isArray(f.questionIds))f.questionIds=[];if(!f.conflicts||typeof f.conflicts!=='object')f.conflicts={};if(!Array.isArray(f.followups))f.followups=[];if(!f.depth||typeof f.depth!=='object')f.depth={};f.stage=Math.max(0,Math.min(12,Number(f.stage)||0));return f;}catch(e){notice='無法讀取原本的 V3 進度，已安全回到首頁；原資料不會主動刪除。';return freshState();}}
function saveState(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(V3_KEY,JSON.stringify(state));}catch(e){notice='此瀏覽器目前無法儲存進度；完成前請不要關閉頁面。';}showNotice();}
function showNotice(){const el=document.getElementById('notice');if(!el)return;el.textContent=notice;el.classList.toggle('hidden',!notice);}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selected(k){return state.selections[k].map(id=>byId[id]).filter(Boolean)}
function names(k){return selected(k).map(c=>c.name).join('、')}
function invalidateDerived(){state.questionIds=[];state.conflictIndex=0;state.conflicts={};state.followups=[];state.depth={};state.completedAt=null;}
function validateName(v){const n=String(v||'').trim(),len=Array.from(n).length;return !n?'先告訴我怎麼稱呼你吧 😊':len<2||len>20?'名字請保留在 2～20 個字元之間 😊':'';}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),2500);}
function openName(){entryView='name';if(!state.startedAt)state.startedAt=new Date().toISOString();saveState();render();setTimeout(()=>document.getElementById('userName')?.focus(),0)}
function submitName(){const i=document.getElementById('userName'),err=validateName(i.value);document.getElementById('nameError').textContent=err;if(err)return;state.name=i.value.trim();if(!state.startedAt)state.startedAt=new Date().toISOString();entryView='';if(state.stage===0)state.stage=1;saveState();render();window.scrollTo(0,0)}
function startNew(){clearTimeout(analysisTimer);state=freshState();state.startedAt=new Date().toISOString();entryView='name';saveState();document.getElementById('resetDialog')?.close();render();window.scrollTo(0,0)}
function continueExploration(){entryView='';render()}
function toggleCard(id){const c=byId[id],k=stageCategory[state.stage];if(!c||!k)return;const list=state.selections[k];const i=list.indexOf(id);if(i>=0){list.splice(i,1);if(k==='ability')delete state.skillEvidence[id];if(k==='value')state.selections.core=state.selections.core.filter(v=>v!==id)}else{const max=limits[k];if(list.length>=max){toast(k==='dealbreaker'?'最多選 3 項排除條件':'最多選 '+max+' 張，請先取消一張');return;}list.push(id)}invalidateDerived();saveState();render();}
function reorderCore(id,target){if(state.stage!==5)return false;const a=state.selections.core,i=a.indexOf(id),j=a.indexOf(target);if(i<0||j<0||i===j)return false;a.splice(i,1);a.splice(j,0,id);invalidateDerived();saveState();render();toast('核心順位已更新 ✨');return true;}
function nudgeCore(id,delta){const a=state.selections.core,i=a.indexOf(id),j=i+delta;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];invalidateDerived();saveState();render();}
function moveCardTo(id,zone){const k=stageCategory[state.stage];if(!k||!['selected','pool'].includes(zone))return false;const list=state.selections[k],on=list.includes(id);if(on===(zone==='selected'))return false;if(!on&&list.length>=limits[k]){toast('先保留最有感的 '+limits[k]+' 張');return false;}toggleCard(id);return true;}
function bindDrag(el){el.onpointerdown=e=>{if(e.button!==0||dragState)return;if(e.pointerType==='touch'&&!e.target.closest('.drag-handle'))return;dragState={el,id:el.dataset.card,choice:el.dataset.choice,pid:e.pointerId,x:e.clientX,y:e.clientY,active:false,ghost:null};el.setPointerCapture?.(e.pointerId)};el.onpointermove=e=>{const d=dragState;if(!d||d.el!==el||d.pid!==e.pointerId)return;if(!d.active&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<8)return;if(!d.active){d.active=true;const r=el.getBoundingClientRect();d.ghost=el.cloneNode(true);d.ghost.classList.add('drag-ghost');d.ghost.setAttribute('aria-hidden','true');d.ghost.style.width=r.width+'px';d.ghost.style.height=Math.min(r.height,240)+'px';document.body.appendChild(d.ghost);el.classList.add('drag-source')}e.preventDefault();d.ghost.style.left=(e.clientX-60)+'px';d.ghost.style.top=(e.clientY-35)+'px';if(e.clientY<90)window.scrollBy(0,-14);else if(e.clientY>window.innerHeight-90)window.scrollBy(0,14);document.querySelectorAll('[data-drop-zone]').forEach(z=>z.classList.remove('drop-over'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-drop-zone]')?.classList.add('drop-over')};const finish=e=>{const d=dragState;if(!d||d.el!==el)return;dragState=null;d.ghost?.remove();el.classList.remove('drag-source');document.querySelectorAll('[data-drop-zone]').forEach(z=>z.classList.remove('drop-over'));if(!d.active)return;suppressClickUntil=Date.now()+350;const target=e.type==='pointercancel'?null:document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-drop-zone]');let moved=false;if(target&&d.id){const over=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-card]');if(state.stage===5&&target.dataset.dropZone==='selected'&&over)moved=reorderCore(d.id,over.dataset.card);if(!moved)moved=moveCardTo(d.id,target.dataset.dropZone)}else if(target&&d.choice!==undefined&&target.dataset.dropZone==='choice'){setConflict('choice',Number(d.choice));moved=true}if(!moved){el.classList.add('drag-reject');setTimeout(()=>el.classList.remove('drag-reject'),220)}};el.onpointerup=finish;el.onpointercancel=finish;el.ondragstart=e=>e.preventDefault()}
function setEvidence(id,level){if(!state.selections.ability.includes(id)||![1,2,3].includes(level))return;state.skillEvidence[id]=level;saveState();render();}
function setConflict(field,value){const id=state.questionIds[state.conflictIndex];if(!id)return;const a=state.conflicts[id]||{choice:null,difficulty:null};if(a[field]!==value){a[field]=value;if(field==='choice')a.difficulty=null;state.conflicts[id]=a;state.followups=[];state.depth={};saveState();render();}}
function profile(){const riasec=Object.fromEntries(Object.keys(RIASEC).map(k=>[k,0]));selected('interest').forEach(c=>c.riasec.forEach((r,i)=>riasec[r]+=i?0.55:1));const skills=selected('ability').map(c=>c.skill);const evidence={};for(const [id,lvl] of Object.entries(state.skillEvidence)){const c=byId[id];if(c)evidence[c.skill]=Math.max(evidence[c.skill]||0,lvl)}const values={};selected('value').forEach(c=>values[c.tag]=(values[c.tag]||0)+1);selected('core').forEach((c,i)=>values[c.tag]=(values[c.tag]||0)+[3,2,1][i]);const env=new Set(selected('environment').map(c=>c.tag));const life=new Set(selected('life').map(c=>c.tag));const deal=new Set(selected('dealbreaker').map(c=>c.risk));const trade={};for(const q of conflicts){const a=state.conflicts[q.id];if(!a||![0,1].includes(a.choice)||![1,2,3].includes(a.difficulty))continue;const chosen=q.options[a.choice].tag,other=q.options[1-a.choice].tag;const cw={1:1,2:.82,3:.62}[a.difficulty],ow={1:0,2:.18,3:.48}[a.difficulty];trade[chosen]=(trade[chosen]||0)+cw;trade[other]=(trade[other]||0)+ow}return{riasec,skills,evidence,values,env,life,deal,trade}}
function maxObj(o){return Math.max(1,...Object.values(o))}
function fitEngine(){const p=profile(),riMax=maxObj(p.riasec),vMax=maxObj(p.values),tMax=maxObj(p.trade);const list=careerFamilies.map(f=>{const interest=f.riasec.reduce((s,r)=>s+p.riasec[r]/riMax,0)/f.riasec.length;const skill=f.skills.reduce((s,k)=>s+(p.skills.includes(k)?1:0),0)/f.skills.length;const evRelevant=f.skills.filter(k=>p.evidence[k]);const evidence=evRelevant.length?evRelevant.reduce((s,k)=>s+({1:.35,2:.68,3:1}[p.evidence[k]]||0),0)/f.skills.length:0;const value=f.values.reduce((s,k)=>s+(p.values[k]||0)/vMax,0)/f.values.length;const env=f.env.reduce((s,k)=>s+(p.env.has(k)?1:0),0)/f.env.length;const life=f.life.length?f.life.reduce((s,k)=>s+(p.life.has(k)?1:0),0)/f.life.length:0;const trade=f.values.reduce((s,k)=>s+(p.trade[k]||0)/tMax,0)/f.values.length;const db=f.risks.filter(r=>p.deal.has(r));let score=.25*interest+.20*skill+.10*evidence+.20*value+.12*env+.08*life+.05*trade-.13*db.length;score=Math.max(0,Math.min(1,score));return{...f,fit:{interest,skill,evidence,value,env,life,trade},dealConflicts:db,score}}).sort((a,b)=>b.score-a.score);const priority=[];for(const x of list){if(priority.length>=3)break;if(x.score>=.52&&x.dealConflicts.length<2)priority.push(x)}const used=new Set(priority.map(x=>x.name));const extended=[];for(const x of list){if(extended.length>=3)break;if(!used.has(x.name)&&x.score>=.39)extended.push(x)}return{profile:p,all:list,priority,extended}}
function pickConflictQuestions(){const p=profile(),relevant=new Set([...Object.keys(p.values),...p.env,...p.life]);return [...conflicts].sort((a,b)=>{const score=q=>q.options.reduce((s,o)=>s+(relevant.has(o.tag)?2:0)+(p.values[o.tag]||0),0);return score(b)-score(a)||Number(a.id.slice(1))-Number(b.id.slice(1))}).slice(0,12).map(q=>q.id)}
function hardConflict(){return state.questionIds.map(id=>conflicts.find(q=>q.id===id)).find(q=>state.conflicts[q.id]?.difficulty===3)}
function generateFollowups(){const e=fitEngine(),p=e.profile,topR=Object.entries(p.riasec).sort((a,b)=>b[1]-a[1])[0]?.[0]||'I',hard=hardConflict(),core=selected('core');const strong=Object.entries(state.skillEvidence).sort((a,b)=>b[1]-a[1])[0]?.[0];const strongCard=byId[strong]||selected('ability')[0];const deal=selected('dealbreaker')[0];return[
{id:'f1',tag:'peak',stanceMode:'none',text:'回想一段你工作或做專案時很投入、很有成就感的經驗。當時你正在做什麼？哪些元素讓你覺得「這很像我」？'},
{id:'f2',tag:'drain',stanceMode:deal?'avoid':'none',text:deal?'你把「'+deal.name+'」列為目前不想接受的條件。過去有什麼經驗讓你特別在意這件事？':'哪一類任務、主管互動或工作情境最容易讓你覺得耗能？真正消耗你的是什麼？'},
{id:'f3',tag:core[0]?.tag||'value',stanceMode:'condition',text:hard?'你在「'+hard.title+'」非常難選。什麼條件改變時，你會願意改選另一邊？':'你目前前三項核心價值是「'+names('core')+'」。如果一份工作無法全部滿足，你最先守住哪一項？底線是什麼？'},
{id:'f4',tag:'life',stanceMode:'condition',text:'你目前的人生需求是「'+names('life')+'」。有哪些時間、收入、照顧責任或生活安排會直接影響你的工作選擇？不必填敏感金額。'},
{id:'f5',tag:'evidence',stanceMode:'none',text:'你選擇的能力包含「'+names('ability')+'」。請用「'+(strongCard?.name||'其中一項能力')+'」舉一個可驗證成果，並寫下一個你願意在 30 天內做的小實驗。'}]}
