function directionInsight(d){
 const matchedSkills=d.skills.filter(k=>profile().skills.includes(k)).map(k=>skillLabels[k]);const proven=d.skills.filter(k=>profile().evidence[k]>=3).map(k=>skillLabels[k]);const selectedEnv=selected('environment').filter(c=>d.env.includes(c.tag)).map(c=>c.name);const core=selected('core').filter(c=>d.values.includes(c.tag)).map(c=>c.name);
 const why=[];if(d.fit.interest>=.5)why.push('興趣傾向');if(matchedSkills.length)why.push('能力');if(proven.length)why.push('能力證據');if(core.length)why.push('核心價值');if(selectedEnv.length)why.push('工作情境');
 const check=d.dealConflicts.length?'這個方向容易碰到你目前排除的「'+d.dealConflicts.map(dbName).join('、')+'」，需先確認頻率、責任邊界與是否為常態。':'目前沒有直接撞上你的排除條件，但仍要查核主管方式、工時與實際任務比例。';
 const suited='較適合你的版本：'+(selectedEnv.length?selectedEnv.slice(0,2).join('＋')+'情境中的':'權責與成果清楚的')+d.name+(core.length?'，並能支持「'+core.slice(0,2).join('、')+'」':'')+'。';
 const less='比較不適合的版本：'+(d.dealConflicts.length?'長期包含「'+d.dealConflicts.map(dbName).join('、')+'」的工作型態。':'職稱相同但責任模糊、回饋不足，或核心任務與你實際興趣落差大的版本。');
 return{why:why.length?'目前由「'+why.join('、')+'」共同支持，不是只靠單一選卡。':'目前交集仍有限，因此更適合先小規模驗證。',check,suited,less,proven};
}
function reflectionInsight(q){return reflectionAnalysis(q).analysis}
function generateReport(){const engine=fitEngine();const core=selected('core').map(c=>c.tag),insights=insightEngine();return{modelVersion:MODEL_VERSION,engine,insights,core,followups:state.followups,generatedAt:new Date().toISOString(),answers:JSON.parse(JSON.stringify(state))}}
function stageValid(){switch(state.stage){case 1:return state.selections.interest.length===5;case 2:return state.selections.ability.length===5;case 3:return state.selections.ability.length===5&&state.selections.ability.every(id=>[1,2,3].includes(state.skillEvidence[id]));case 4:return state.selections.value.length===5;case 5:return state.selections.core.length===3;case 6:return state.selections.environment.length===4;case 7:return state.selections.life.length===3;case 8:return true;case 9:{const id=state.questionIds[state.conflictIndex],a=state.conflicts[id];return a&&[0,1].includes(a.choice)&&[1,2,3].includes(a.difficulty)}case 10:return state.followups.length===5&&state.followups.every(q=>state.depth[q.id]?.text.trim());default:return true}}
function nextStep(){if(!stageValid()){const msg={1:'請選滿 5 張興趣卡。',2:'請選滿 5 張能力卡。',3:'請完成 5 項能力的經驗確認。',4:'請選滿 5 張價值觀卡。',5:'請留下並排好 3 項核心價值。',6:'請選滿 4 張工作情境卡。',7:'請選滿 3 張人生需求卡。',9:'請完成二選一與難選程度。',10:'請回答全部 5 題；尚未想清楚也可以寫目前的疑問。'}[state.stage]||'請完成這一步。';document.getElementById('error').textContent=msg;return}if(state.stage===8){if(!state.questionIds.length)state.questionIds=pickConflictQuestions();state.stage=9}else if(state.stage===9){if(state.conflictIndex<11)state.conflictIndex++;else{if(!state.followups.length)state.followups=generateFollowups();state.stage=10}}else if(state.stage===10){state.stage=11;saveState();render();analysisTimer=setTimeout(()=>{state.stage=12;state.completedAt=new Date().toISOString();saveState();render();window.scrollTo(0,0)},900);return}else state.stage++;saveState();render();window.scrollTo(0,0)}
function prevStep(){if(state.stage===9&&state.conflictIndex>0)state.conflictIndex--;else if(state.stage===12)state.stage=10;else state.stage=Math.max(0,state.stage-1);saveState();render();window.scrollTo(0,0)}
function renderHome(){return '<section class="home"><div><div class="eyebrow">一場更完整的職涯對話</div><h1>不是只問「我適合什麼」，<br>而是看見<br><em>我怎麼做選擇。</em></h1><p class="lead">從興趣、能力證據、核心價值、工作情境、人生需求與真實取捨，建立你的職涯決策地圖。</p><button class="primary" id="start">開始我的職涯探索　→</button><p class="small" style="margin-top:16px">沒有標準答案；結果是探索假設，不是職業命定。</p></div><div class="deck-preview" aria-label="探索流程"><div class="preview-card"><div class="index">01</div><div><b>分開看見自己</b><br><span>興趣 × 能力證據 × 價值 × 情境</span></div></div><div class="preview-card"><div class="index">02</div><div><b>取捨，看見底線</b><br><span>人生需求 × 排除條件 × 12 個情境</span></div></div><div class="preview-card"><div class="index">03</div><div><b>形成決策地圖</b><br><span>25 個職涯群 × 職缺檢查表 × 90 天行動</span></div></div></div></section><div class="home-foot"><span>✓ 進度僅保存在此瀏覽器</span><span>✓ 可回頭修改與下載報告</span><span>RIASEC 僅作興趣分類參考</span></div>'}
function renderProfile(){return '<section class="profile-page"><div class="profile-symbol">✨</div><h1>先認識你一下吧</h1><p class="intro">輸入你喜歡的稱呼，這份職涯決策報告會專屬於你。</p><form id="profileForm"><label for="userName">姓名／暱稱</label><input id="userName" autocomplete="nickname" placeholder="例如：Clair" value="'+esc(state.name)+'"><div id="nameError" class="name-error"></div><p class="small">2～20 個字元；只保存在這個瀏覽器。</p><button class="primary" type="submit">開始探索</button></form><button id="backHome">← 返回首頁</button></section>'}
function renderResume(){return '<section class="profile-page"><div class="profile-symbol">📖</div><h1>找到一份尚未完成的探索紀錄</h1><p>'+esc(state.name||'你的')+'選擇還留在這個瀏覽器。</p><p class="small">目前進度：'+esc(stages[state.stage])+'</p><button id="continue" class="primary">繼續上次探索</button><div class="actions"><button id="newUser">開始新的探索</button></div></section>'}
function renderTrail(){const pts=[['🌱','興趣',1],['✨','能力',2],['🔎','證據',3],['💛','價值',4],['🌿','情境',6],['🎯','人生',7],['🚫','排除',8],['⚖️','取捨',9],['💬','深度',10],['🌟','結果',11]];return '<nav class="trail" aria-label="探索階段">'+pts.map(([ic,t,s],i)=>{const end=pts[i+1]?.[2]||13,active=state.stage>=s&&state.stage<end;return '<span class="trail-item '+(active?'active':state.stage>=end?'done':'')+'">'+(state.stage>=end?'✓':ic)+' '+t+'</span>'}).join('')+'</nav>'}
function renderGameCard(c,k,on){const rank=state.selections[k]?.indexOf(c.id)+1;let tags='';if(c.riasec)tags='<span class="mini-tags">'+c.riasec.map(r=>'<span class="mini-tag riasec">'+r+'</span>').join('')+'</span>';return '<button type="button" class="card '+(on?'selected':'')+'" data-card="'+c.id+'" aria-pressed="'+on+'"><span class="card-top"><span>'+(k==='core'&&on?'<span class="core-rank">第 '+rank+' 順位</span>':categoryNames[c.id.split('-')[0]])+'</span><span class="drag-handle" aria-hidden="true">⠿</span></span><span class="card-icon" aria-hidden="true">'+cardIcon(c)+'</span><b>'+esc(c.name)+'</b><p>'+esc(c.description)+'</p>'+tags+'<span class="tap-hint">'+(on?'✓ 已選 · 點一下移除':'拖入我的選擇 · 或點一下')+'</span></button>'}
function renderCards(){const k=stageCategory[state.stage],chosen=state.selections[k],list=k==='core'?selected('value'):cards[k],limit=limits[k];const heads={interest:'先從你真正喜歡投入的事情開始。',ability:'哪些事情，你通常做得比較順手？',value:'如果工作有很多條件，你最不想失去什麼？',core:'留下最重要的三張，排出真正的優先順序。',environment:'什麼樣的工作情境，讓你比較能發揮？',life:'現在這個人生階段，你最需要工作支持什麼？',dealbreaker:'哪些條件，是你目前最不想接受的？'};const note=k==='dealbreaker'?'可不選，最多 3 項；它會成為推薦方向的優先查核條件。':'請選出 '+limit+' 張。拖進「我的選擇」，也可以直接點擊。';return '<div class="stage-head"><h2>'+heads[k]+(k==='dealbreaker'?'<span class="optional-chip">選填</span>':'')+'</h2><p class="intro">'+note+'</p></div><div class="card-board"><section class="card-pool" data-drop-zone="pool"><h3 class="zone-title">待探索卡牌 <span class="small">按住 ⠿ 可拖曳</span></h3><div class="cards">'+list.filter(c=>!chosen.includes(c.id)).map(c=>renderGameCard(c,k,false)).join('')+'</div></section><section class="my-cards" data-drop-zone="selected"><h3 class="zone-title">我的選擇 <span class="selection-count">已選 '+chosen.length+' / '+limit+'</span></h3><div class="cards">'+chosen.map(id=>{const c=byId[id],h=renderGameCard(c,k,true);return k==='core'?'<div class="core-wrap">'+h+'<div class="rank-controls"><button type="button" data-nudge="-1" data-id="'+id+'" aria-label="上移">↑ 上移</button><button type="button" data-nudge="1" data-id="'+id+'" aria-label="下移">↓ 下移</button></div></div>':h}).join('')+'</div>'+(!chosen.length?'<div class="empty-tray"><span>✧</span>把有感覺的卡牌放在這裡</div>':'')+'</section></div>'+(chosen.length?'<details class="reflection"><summary>想多想一點？看看已選卡牌的探索問題</summary>'+chosen.map(id=>byId[id]?.question?'<p><b>'+esc(byId[id].name)+'</b>：'+esc(byId[id].question)+'</p>':'').join('')+'</details>':'')}
function renderEvidence(){const ids=state.selections.ability,count=ids.filter(id=>[1,2,3].includes(state.skillEvidence[id])).length;return '<div class="stage-head"><h2>哪些能力，已經被你的經驗證明？</h2><p class="intro">你剛才選出了 5 項自己擅長的能力。這一步不是重新挑能力，而是替每一項能力標記目前的「經驗證據」。完成後，報告會把能力分成「已有經驗支持」、「發展中」與「尚待驗證」。</p><p class="evidence-count">已完成 '+count+' / 5 項能力確認</p></div><div class="evidence-grid">'+ids.map(id=>{const c=byId[id],lvl=state.skillEvidence[id]||0;return '<section class="evidence-card '+(lvl?'selected':'')+'"><div class="badge-row"><span class="card-icon">'+cardIcon(c)+'</span><span class="mini-tag">'+skillLabels[c.skill]+'</span></div><h3>'+esc(c.name)+'</h3><p>'+esc(c.question)+'</p><p class="small" style="margin:12px 0 6px"><b>這項能力目前有多少真實經驗支持？</b></p><div class="evidence-levels"><button data-evidence="'+id+'" data-level="3" class="'+(lvl===3?'selected':'')+'"><b>✨ 有具體成果</b><br><span class="small">我能說出實際案例、作品、成果或他人的回饋</span></button><button data-evidence="'+id+'" data-level="2" class="'+(lvl===2?'selected':'')+'"><b>🌱 有相關經驗</b><br><span class="small">我做過這類事情，但成果或證據還沒有整理完整</span></button><button data-evidence="'+id+'" data-level="1" class="'+(lvl===1?'selected':'')+'"><b>💭 還需要驗證</b><br><span class="small">目前主要是自己的感覺，需要更多實際經驗確認</span></button></div></section>'}).join('')+'</div><p class="v3-note">這不是能力考試，也沒有好壞答案。請照目前真實經驗選擇；五項都完成後即可進入下一步。</p>'}
function renderConflict(){const q=conflicts.find(q=>q.id===state.questionIds[state.conflictIndex]);if(!q)return '<p>題目尚未準備，請返回上一頁。</p>';const a=state.conflicts[q.id]||{},on=[0,1].includes(a.choice);return '<div class="eyebrow">情境 '+(state.conflictIndex+1)+' / 12</div><h2>如果只能先選一邊？</h2><p class="intro">'+esc(q.title)+' · 選現在更接近你的答案，再標記有多難選。</p><div class="choice-grid '+(on?'chosen':'')+'">'+q.options.map((o,i)=>(i?'<span class="versus">VS</span>':'')+'<button class="choice '+(a.choice===i?'selected':'')+'" data-choice="'+i+'"><span class="drag-handle">⠿</span><span>'+esc(o.text)+'</span></button>').join('')+'</div><div class="choice-target" data-drop-zone="choice"><span class="small">我的選擇</span><div class="'+(on?'chosen-choice':'')+'">'+(on?esc(q.options[a.choice].text):'把卡片拖到這裡，或直接點選')+'</div></div>'+(on?'<section class="panel difficulty-panel"><h3>這題對你來說有多難選？</h3><div class="difficulty">'+['😊 很容易','🤔 有點猶豫','😵 非常難選'].map((d,i)=>'<button data-difficulty="'+(i+1)+'" class="'+(a.difficulty===i+1?'selected':'')+'">'+d+'</button>').join('')+'</div><p class="small" style="margin-top:14px">「非常難選」代表兩邊都要保留，不會把未選的一邊當成不重要。</p></section>':'')}
function depthGuide(q){
 if(q.tag==='peak')return{title:'作答建議',items:['請寫一段具體經驗，而不只寫工具、職稱或專案名稱。','可依序說明：當時的任務／目標、你實際做了什麼、哪個環節最投入、最後有什麼成果或回饋。','建議回答 2～5 句，讓報告有足夠資訊區分「喜歡任務本身」與「喜歡完成成果的感覺」。'],placeholder:'例如：當時我要完成……；我主動負責……；最投入的是……；最後得到……成果／回饋。'};
 if(q.tag==='drain')return{title:'作答建議',items:['請描述一個實際情境，而不只寫「很累」「薪水低」等結論。','可說明：發生了什麼、真正讓你消耗的是哪個因素、它如何影響工作感受，以及你希望下次有哪些不同。'],placeholder:'例如：當時的情境是……；最消耗我的不是工作量，而是……；下次我希望……。'};
 if(q.tag==='evidence')return{title:'作答建議',items:['請選一項能力，用「任務－行動－結果－證據」來寫。','證據可以是作品、完成成果、數字、流程改善、主管／客戶回饋或可展示紀錄。','最後補上一個 30 天內可以完成的小實驗，用來繼續驗證這項能力與興趣。'],placeholder:'例如：我負責……；我採取……做法；最後……；可以用……證明；接下來 30 天我會……。'};
 if(q.stanceMode==='avoid')return{title:'作答建議',items:['請說明你為什麼把這項條件列為排除或風險項目。','可寫：過去發生過什麼、真正不能接受的是哪一部分，以及在什麼條件下你仍可能接受。'],placeholder:'例如：過去曾遇到……；我最在意的是……；如果……，我仍可以接受。'};
 if(q.tag==='life')return{title:'作答建議',items:['請把「人生需求」轉成可以比較工作的實際條件。','可從工時、通勤、收入穩定、休息、照顧責任、進修或其他固定安排思考；不需要填敏感金額。','盡量寫出最低可接受標準，而不只寫理想狀態。'],placeholder:'例如：我目前需要保留……時間；通勤希望……；如果工作需要……，我的最低可接受條件是……。'};
 return{title:'作答建議',items:['請先說明你會優先保留什麼，再寫出底線與可交換條件。','盡量把抽象價值改寫成實際工作條件，例如工時、授權範圍、回饋方式或發展機會。'],placeholder:'例如：我會先保留……；最低標準是……；如果……，我可以接受交換。'};
}
function answerDetailNote(q){const a=state.depth[q.id]||{},n=Array.from((a.text||'').trim()).length;if(!n)return'';if(n<12)return'目前回答較精簡，報告只能確認你指出了這項經驗／條件，尚不足以進一步區分其關鍵因素。建議回到題目補充情境、行動、結果或底線。';if(n<35)return'目前已有基本脈絡；若再補充具體行動、成果或最低條件，後續分析會更容易轉成職缺查核與行動建議。';return'目前回答已提供一定的情境資訊，可與前面的選卡、能力證據與決策邊界進行交叉整理。'}
function reflectionAnalysis(q){const a=state.depth[q.id]||{},interests=selected('interest').map(c=>c.name),abilities=selected('ability').map(c=>c.name),strong=selected('ability').filter(c=>state.skillEvidence[c.id]===3).map(c=>c.name),core=selected('core').map(c=>c.name),env=selected('environment').map(c=>c.name),life=selected('life').map(c=>c.name),deal=selected('dealbreaker').map(c=>c.name),detail=answerDetailNote(q);let analysis='',connection='',use='',next='';
 if(q.tag==='peak'){analysis='這題用來辨識「哪些工作元素會提高你的投入感與成就感」。系統不從自由文字猜測心理狀態，而是把這段經驗當作一個可回顧的工作情境證據。';connection='可與你前面選到的興趣「'+(interests.slice(0,3).join('、')||'尚待確認')+'」及能力「'+(abilities.slice(0,3).join('、')||'尚待確認')+'」交叉比對'+(strong.length?'；其中已有具體成果支持的能力包含「'+strong.slice(0,2).join('、')+'」。':'。');use='未來比較職缺時，請觀察工作內容是否能重現這段經驗中的任務型態、解題方式、創作／實作過程或完成成果的回饋機制。';next='若想讓分析更精準，可再補充：你當時最投入的是「做什麼」、使用「什麼方法」，還是看見「什麼結果」？';}
 else if(q.tag==='drain'){analysis='這題用來辨識容易造成消耗的工作情境，重點不是判定你「不能做」某類工作，而是找出需要事先查核的風險來源。';connection='目前可與你的工作情境偏好「'+(env.slice(0,3).join('、')||'尚待確認')+'」'+(deal.length?'及排除條件「'+deal.slice(0,3).join('、')+'」':'')+'一起閱讀。';use='未來看 JD、面試或比較 Offer 時，可把這段經驗轉成具體查核問題，例如頻率、持續時間、責任邊界與可否事先協調。';next='建議再補充：真正讓你耗能的是工作量、不可預期、主管互動、責任不清，還是其他因素？';}
 else if(q.tag==='evidence'){analysis='這題用來把「我覺得自己會」轉成「我能用成果說明」。可驗證成果越具體，越適合放進履歷、作品集或面試案例。';connection='你前面選到的能力包括「'+(abilities.slice(0,4).join('、')||'尚待確認')+'」'+(strong.length?'，其中「'+strong.slice(0,3).join('、')+'」已標記為有具體成果。':'。');use='建議把這段經驗整理成 STAR／案例格式：情境、任務、你的行動、結果與證據，之後可直接轉用到履歷與面試。';next='再確認一件事：這項成果是否能由作品、數字、前後差異、文件或他人回饋支持？';}
 else if(q.tag==='life'){analysis='這題用來把目前人生需求轉成職涯決策限制，避免只從職稱或工作內容判斷適不適合。';connection='你目前選到的人生需求包含「'+(life.join('、')||'尚待確認')+'」，核心價值則包含「'+(core.join('、')||'尚待確認')+'」。';use='請把回答中的條件轉成「最低可接受標準」，例如工時、通勤、彈性、收入穩定或固定時段，之後可直接用來比較職缺。';next='若目前仍偏抽象，建議再補一個可以明確判斷「符合／不符合」的標準。';}
 else if(q.stanceMode==='avoid'){const boundary=a.stance==='core'?'你已將此項標記為目前優先避開。':a.stance==='trade'?'你已標記為符合特定條件時可以接受。':a.stance==='unclear'?'你目前仍需要更多資訊才能判斷。':'你尚未設定明確的決策邊界。';analysis='這題用來釐清排除條件背後真正需要避免的風險，而不是把某一類工作直接判定為不適合。'+boundary;connection=deal.length?'目前排除條件包含「'+deal.join('、')+'」，可和這段經驗一起判斷哪些風險最需要在面試前確認。':'目前沒有其他明確排除條件，可先把這段經驗當作待查核線索。';use='把回答改寫成可詢問的條件，例如「常態發生的頻率是多少？」「什麼情況算例外？」「是否有補償或事前協調機制？」';next='若你願意條件式接受，請再寫清楚「什麼條件成立時可以接受」。';}
 else{const boundary=a.stance==='core'?'你已把它標記為下一份工作想保留的條件。':a.stance==='trade'?'你已標記為符合條件時可交換。':a.stance==='unclear'?'你目前仍需要更多資訊才能判斷。':'你尚未設定明確的決策邊界。';analysis='這題用來把抽象價值轉成可執行的職涯邊界。'+boundary;connection='可與核心價值「'+(core.join('、')||'尚待確認')+'」及工作情境「'+(env.slice(0,3).join('、')||'尚待確認')+'」一起判讀，確認哪些條件是真正需要優先查核的。';use='將回答中的底線轉成面試問題或 Offer 比較欄位，比單純記住「我重視某價值」更有決策作用。';next='若回答中只有理想狀態，建議再補：最低標準、可接受例外，以及何時需要重新評估。';}
 return{analysis,connection,use,next,detail};}
